name: hackapp_azure
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.11
  - pip
  - pip:
    - streamlit
    - langchain
    - langchain-openai
    - chromadb
    - BeautifulSoup4
    - pypdf
    - pdfplumber



